config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  get 'home/index'
  get 'contact-us', to: 'home#contact_us'
  post 'contact-us', to: 'home#contact_us'
  get 'create', to: 'home#create'
  get 'privacy-policy', to: 'home#privacy_policy'
  get 'empresas', to: 'home#business'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard_shop', to: 'dashboard#shop'
  put 'users_add_onesignal_id', to: 'users#add_onesignal_id', defaults: { format: 'json' }
  get 'my_account', to: 'users#my_account'
  put 'update_account', to: 'users#update_account'
  get 'states_provinces/:country', to: 'application#states_provinces'
  get 'cities/:country/:state_province', to: 'application#cities'

  # devise_for :users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :replacement_requests do
    collection do
      get :closed
    end
    member do
      get :ignore
    end
  end
  resources :vehicles
  resources :shops
  resources :replacement_proposals do
    member do
      get :ignore
      get :accept
    end
  end
  defaults format: :json do
    get :search, to: 'replacement_proposals#search', as: 'replacement_proposal_search'
  end

  namespace :dario do
    resources :res_name
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    redirect_to dashboard_shop_path if current_user.has_role?(:shop)
    @my_vehicles = current_user.vehicles.count
    @my_requests = current_user.replacement_requests.pending.count
    @my_c_requests = current_user.replacement_requests.closed.count
  end

  def shop
    @title += ' Empresas'
    redirect_to new_shop_path, alert: 'Por favor registre un local' if current_user.shops.count == 0
    @my_shops = current_user.shops.count
    @pending_requests = ReplacementRequest.pending.count
    @accepted_proposals = ReplacementProposal.accepted.count
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="row justify-content-center dashboard-buttons">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <div class="row">
      <div class="col-sm-12 col-lg-6">
        <%= link_to new_replacement_request_path, data: { turbolinks: false }, class:"btn btn-outline-primary btn-lg btn-block position-relative" do %>
          <i class="material-icons text-dark mr-3" style="font-size: 3rem;">flare</i>
          Solicitar repuesto
        <% end %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <%= link_to replacement_requests_path, data: { turbolinks: false }, class:"btn btn-outline-success btn-lg btn-block position-relative" do %>
          <i class="material-icons text-dark mr-2" style="font-size: 3rem;">fact_check</i>
          Mis solicitudes
          <span class="badge badge-red position-absolute badge-ruc">
            <%= @my_requests %>
          </span>
        <% end %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <%= link_to closed_replacement_requests_path, data: { turbolinks: false }, class:"btn btn-outline-info btn-lg btn-block position-relative" do %>
          <i class="material-icons text-dark mr-2" style="font-size: 3rem;">summarize</i>
          Solicitudes cerradas
          <span class="badge badge-red position-absolute badge-ruc">
            <%= @my_c_requests %>
          </span>
        <% end %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <%= link_to vehicles_path, class:"btn btn-outline-warning btn-lg btn-block position-relative" do %>
          <i class="material-icons text-dark mr-2" style="font-size: 3rem;">commute</i>
          Mis vehículos
          <span class="badge badge-red position-absolute badge-ruc">
            <%= @my_vehicles %>
          </span>
        <% end %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <%= link_to new_vehicle_path, data: { turbolinks: false }, class:"btn btn-outline-success btn-lg btn-block position-relative" do %>
          <i class="material-icons text-dark mr-3" style="font-size: 3rem;">add_circle_outline</i>
          Agregar vehículo
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>
<br>
<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= render 'home/ad_example' %>
    </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

app/views/dashboard/shop.html.erb
<div class="row justify-content-center dashboard-buttons">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <div class="row">
      <div class="col-sm-12 col-lg-6">
        <%= link_to replacement_requests_path, data: { turbolinks: false }, class:"font-weight-bolder btn btn-outline-primary btn-lg btn-block" do %>
          <i class="material-icons text-dark mr-3" style="font-size: 3rem;">flare</i>
          Solicitudes pendientes
        <% end %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <%= link_to replacement_proposals_path, data: { turbolinks: false }, class:"font-weight-bolder btn btn-outline-success btn-lg btn-block" do %>
          <i class="material-icons text-dark mr-2" style="font-size: 3rem;">summarize</i>
          Mis propuestas
        <% end %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <%= link_to shops_path, class:"font-weight-bolder btn btn-outline-warning btn-lg btn-block" do %>
          <i class="material-icons text-dark mr-3" style="font-size: 3rem;">store</i>
          Mis locales
        <% end %>
      </div>
      <div class="col-sm-12 col-lg-6">
        <%= link_to new_shop_path, data: { turbolinks: false }, class:"font-weight-bolder btn btn-outline-warning btn-lg btn-block" do %>
          <i class="material-icons text-dark mr-2" style="font-size: 3rem;">add_circle_outline</i>
          Agregar más locales
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>
<br>
<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= render 'home/ad_example' %>
    </div>
  <div class="col-md-1 col-sm-1"></div>
</div>