config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  get 'home/index'
  get 'contact-us', to: 'home#contact_us'
  post 'contact-us', to: 'home#contact_us'
  get 'create', to: 'home#create'
  get 'privacy-policy', to: 'home#privacy_policy'
  get 'empresas', to: 'home#business'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard_shop', to: 'dashboard#shop'
  put 'users_add_onesignal_id', to: 'users#add_onesignal_id', defaults: { format: 'json' }
  get 'my_account', to: 'users#my_account'
  put 'update_account', to: 'users#update_account'
  get 'states_provinces/:country', to: 'application#states_provinces'
  get 'cities/:country/:state_province', to: 'application#cities'

  # devise_for :users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :replacement_requests do
    collection do
      get :closed
    end
    member do
      get :ignore
    end
  end
  resources :vehicles
  resources :shops
  resources :replacement_proposals do
    member do
      get :ignore
      get :accept
    end
  end
  defaults format: :json do
    get :search, to: 'replacement_proposals#search', as: 'replacement_proposal_search'
  end

  namespace :dario do
    resources :res_name
  end
end

app/models/replacement_request.rb
# frozen_string_literal: true

class ReplacementRequest < ApplicationRecord
  resourcify

  belongs_to :user
  belongs_to :vehicle
  has_many :replacement_proposals
  has_many_attached :photos

  validates :short_name, :country, :state_province, :city, presence: true

  scope :pending, -> { where(state: %w[created answered]) }
  scope :closed, -> { where(state: 'closed') }
  scope :answered, -> { where(state: 'answered') }
  scope :recent, ->(number) { order(id: :desc).limit(number) }
end

app/controllers/replacement_requests_controller.rb
# frozen_string_literal: true

class ReplacementRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_replacement_request, only: %i[ignore]
  load_and_authorize_resource

  # GET /replacement_requests or /replacement_requests.json
  def index
    @rr_query = ReplacementRequest.accessible_by(current_ability).order(id: :desc).ransack(params[:q])
    @replacement_requests = @rr_query.result(distinct: true).includes(:vehicle).includes(:replacement_proposals).where.not(state: ['closed'])

    if current_user.has_role? :shop
      @replacement_requests = @replacement_requests.where.not(id: IgnoredRequest.mine(current_user).map do |ir|
                                                                    ir.replacement_request_id
                                                                  end)
    end

    if params[:filters].present?
      if filters_params[:brands].present?
        @replacement_requests = @replacement_requests.joins(:vehicle).where('vehicles.brand IN (?)',
                                                                            filters_params[:brands])
      end
      if filters_params['years'].present?
        @replacement_requests = @replacement_requests.joins(:vehicle).where('vehicles.year IN (?)',
                                                                            filters_params['years'])
      end
    end

    @all_brands = Vehicle.all_brands
    @all_years = Vehicle.all_years
  end

  # GET /replacement_requests/closed or /replacement_requests/closed.json
  def closed
    @rr_query = ReplacementRequest.accessible_by(current_ability).order(id: :desc).ransack(params[:q])
    @replacement_requests = @rr_query.result(distinct: true).includes(:vehicle).where(state: 'closed')
    if current_user.has_role? :shop
      @replacement_requests = @replacement_requests.where.not(id: IgnoredRequest.mine(current_user).map do |ir|
                                                                    ir.replacement_request_id
                                                                  end)
    end
  end

  # GET /replacement_requests/1 or /replacement_requests/1.json
  def show
    redirect_to replacement_requests_url
  end

  # GET /replacement_requests/new
  def new
    @title = 'Enviar solicitud de repuesto'
    redirect_to new_vehicle_path, alert: 'Primero debe registrar un vehículo.' if current_user.vehicles.count == 0
    @replacement_request = ReplacementRequest.new
    @replacement_request.user_id = current_user.id
  end

  # GET /replacement_requests/1/edit
  def edit
    @title = "Editar solicitud de repuesto para #{@replacement_request.short_name} del vehículo #{@replacement_request.vehicle.brand} #{@replacement_request.vehicle.model} #{@replacement_request.vehicle.year}"
  end

  # POST /replacement_requests or /replacement_requests.json
  def create
    @replacement_request = ReplacementRequest.new(replacement_request_params)
    @replacement_request.user_id = current_user.id
    @replacement_request.state = 'created'

    # TODO: Enviar notificaciones

    respond_to do |format|
      if @replacement_request.save

        current_user.add_role :customer, @replacement_request
        PushNotificationsHelper.new_request_created(@replacement_request,
                                                    new_replacement_proposal_path(replacement_request_id: @replacement_request.id))

        # send emails to users without push
        shops_users = User.with_role(:shop).where(onesignal_id: nil)
        if shops_users.count > 0
          shops_users.each do |user|
            ReplacementMailer.new_request(user, @replacement_request).deliver_later
          end
        end

        format.html do
          redirect_to replacement_requests_url,
                      notice: 'Solicitud creada correctamente, notificamos a las empresas, ahora están preparando sus propuestas.'
        end
        format.json { render :show, status: :created, location: @replacement_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @replacement_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replacement_requests/1 or /replacement_requests/1.json
  def update
    respond_to do |format|
      if @replacement_request.update(replacement_request_params)
        format.html { redirect_to replacement_requests_url, notice: 'Solicitud actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @replacement_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @replacement_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replacement_requests/1 or /replacement_requests/1.json
  def destroy
    @replacement_request.state = 'closed'
    @replacement_request.save(validate: false)
    respond_to do |format|
      format.html { redirect_to replacement_requests_url, notice: 'Solicitud eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  # GET /replacement_requests/1/ignore or /replacement_requests/1/ignore.json
  def ignore
    IgnoredRequest.create(user: current_user, replacement_request: @replacement_request)
    redirect_to replacement_requests_url, warning: 'Solicitud ignorada correctamente.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_replacement_request
    @replacement_request = ReplacementRequest.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def replacement_request_params
    params.require(:replacement_request).permit(:user_id, :vehicle_id, :part_number, :short_name, :description,
                                                :country, :state_province, :city, photos: [])
  end

  def filters_params
    params.require(:filters).permit(brands: [], years: [])
  end
end

app/views/replacement_requests/_form.html.erb
<%= form_with(model: replacement_request) do |form| %>
  <% if replacement_request.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2>
        <%= I18n.t("errors.messages.not_saved", count: replacement_request.errors.count, resource: replacement_request.class.model_name.human.downcase) %>
      </h2>

      <ul>
        <% replacement_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-header card-header-primary">
      <p class="card-category">Describa el repuesto que requiere lo mejor posible</p>
    </div>
    <div class="card-body">

      <div class="form-group">
        <%= form.label :vehicle_id, "Vehículo", class:"bmd-label-floating" %>
        <select class="form-control" name="replacement_request[vehicle_id]" id="replacement_request_vehicle_id" >
          <%= options_for_select(current_user.vehicles.collect{ |t| [ "#{t.brand} #{t.model} #{t.year}", t.id ] }) %>
        </select>
      </div>

      <div class="form-group">
        <%= form.label :short_name, "Nombre", class:"bmd-label-floating" %>
        <%= form.text_field :short_name, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :country, class:"bmd-label-floating" %>
        <select class="form-control" name="replacement_request[country]" id="replacement_request_country">
          <option>Seleccione...</option>
          <%= options_for_select( CS.countries.collect{ |t| [ t.last, t.first ] }, @replacement_request.country ) %>
        </select>
      </div>

      <div class="form-group">
        <%= form.label :state_province, class:"bmd-label-floating" %>
        <select class="form-control" name="replacement_request[state_province]" id="replacement_request_state_province">
          <% if @replacement_request.country.present? %>
            <%= options_for_select( CS.states(@replacement_request.country).collect{ |st| [ st.last, st.first ] }, @replacement_request.state_province ) %>
          <% end %>
        </select>
      </div>

      <div class="form-group">
        <%= form.label :city, class:"bmd-label-floating" %>
        <select class="form-control" name="replacement_request[city]" id="replacement_request_city">
          <% if @replacement_request.state_province.present? && @replacement_request.country.present? && @replacement_request.country != 'Seleccione...'  %>
            <%= options_for_select( CS.cities(@replacement_request.state_province, @replacement_request.country).collect{ |ct| [ ct, ct ] }, @replacement_request.city ) %>
          <% end %>
        </select>
      </div>

      <div class="form-group">
        <%= form.label :description, "Descripción", class:"bmd-label-floating" %>
        <%= form.text_area :description, class:"form-control", rows: 4 %>
      </div>

      <div class="form-group">
        <%= form.label :photos, "Agregar Fotos", class:"text-primary btn btn-outline-primary btn-sm" %>
        <%= form.file_field :photos, class:"form-control-file", multiple: true %>
        <div class="add_photo row"></div>
      </div>
    </div>
    <div class="card-footer">
      <div class="stats align-items-center">
        <%= form.submit 'Guardar', class:"text-info btn btn-outline-info btn-sm" %>
        &nbsp;&nbsp;
        <%= link_to 'Cancelar', replacement_requests_path, data: { turbolinks: false }, class:"text-danger btn btn-outline-danger btn-sm" %>
      </div>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  replacement_request_photos.onchange = evt => {
    const v_files = Array.from(replacement_request_photos.files);
    console.log(v_files);
    v_files.forEach(item => {
      console.log(item);
      if (item) {
        prev_photo = $('<div class="col-sm-12 col-md-4"><img src="'+URL.createObjectURL(item)+'" alt="your image" style="width: 100%; display: block;" /></div>');
        $('.add_photo').append(prev_photo);
      }
    });
  }
  $('#replacement_request_country').change(function(){
    var input_state = $('#replacement_request_state_province');
    $.getJSON('/states_provinces/' + $(this).val(), function(data){
      input_state.empty();
      input_state.append('<option>Seleccione...</option>');
      $.each(data, function(i, j){
        var opt = '<option value='+ i +'>'+ j +'</optio>';
        input_state.append(opt);
      });
    });
  });
  $('#replacement_request_state_province').change(function(){
    var input_city = $('#replacement_request_city');
    $.getJSON('/cities/' + $('#replacement_request_country').val() + '/' + $(this).val(), function(data){
      input_city.empty();
      input_city.append('<option>Seleccione...</option>');
      $.each(data, function(i, j){
        var opt = '<option value='+ j +'>'+ j +'</optio>';
        input_city.append(opt);
      });
    });
  });
</script>

app/views/replacement_requests/_request_item.html.erb
<div class="card col-sm-12 <%= params[:replacement_request_id].present? ? 'col-lg-12' : 'col-lg-4' %>">
  <div class="card-header card-header-success">
    <div class="row">
      <div class=" col-sm-12 col-md-12">
        <p class="card-category"><%= replacement_request.updated_at.strftime('%d/%m/%Y') %> </p>
      </div>
    </div>
  </div>
  <div class="card-body request-content">
    <div class="row">
      <% if replacement_request.photos.any? %>
        <div class="col-sm-12 col-md-5">
          <% if replacement_request.photos.size == 1 %>
            <div class="image-element">
              <% if replacement_request.photos.first.representable? && (["image/png", "image/jpeg", "image/png", "image/gif"].include?(replacement_request.photos.first.content_type)) %>
                <%= image_tag replacement_request.photos.first.variant(resize_to_limit: [150, 150]), class: "img-fluid rounded mx-auto d-block" %>
              <% else %>
                <%= link_to rails_blob_path(replacement_request.photos.first, disposition: "attachment") do %>
                  <div class="download-icon">
                    <span class="material-icons"> cloud_download </span>
                  </div>
                  <%= image_tag "quien_tiene_logo_n.png", alt: "Descargue el archivo", width: 150 %>
                <% end %>
              <% end %>
            </div>
          <% else %>
            <div class="image-gallery">
              <% replacement_request.photos.each_with_index do |photo, index| %>
                <div class="image-element">
                  <% if photo.representable? && (["image/png", "image/jpeg", "image/png", "image/gif"].include?(photo.content_type)) %>
                    <%= image_tag photo.variant(resize_to_limit: [150, 150]), class: "img-fluid rounded mx-auto d-block" %>
                  <% else %>
                    <%= link_to rails_blob_path(photo, disposition: "attachment") do %>
                      <div class="download-icon">
                        <span class="material-icons"> cloud_download </span>
                      </div>
                      <%= image_tag "quien_tiene_logo_n.png", alt: "Descargue el archivo", width: 150 %>
                    <% end %>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="col-sm-12 <%= replacement_request.photos.any? ? 'col-md-7' : 'col-md-12'%>">
        <h2 class="card-category text-dark"><%= replacement_request.vehicle.brand %> <%= replacement_request.vehicle.model %> <%= replacement_request.vehicle.year %> </h2>

        <h3><%= replacement_request.short_name %></h3>

        <% if replacement_request.part_number.present? %>
          <h4>P/N: <%= replacement_request.part_number %></h4>
        <% end %>
        <h5>
          <%= replacement_request.description.html_safe %>
        </h5>
        <h5 class="text-dark">
          <% if replacement_request.city.present? %>
            <span class="material-icons text-success mt-1" style="position: relative; top: 5px;">location_city</span> <%= replacement_request.city %>
          <% end %>
        </h5>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="align-items-center">
        <% if can?(:manage, replacement_request) && replacement_request.state != 'closed' %>
          <%= link_to edit_replacement_request_path(replacement_request), class:"text-info btn btn-outline-info btn-sm" do %>
            <i class="material-icons text-dark mr-2" style="top: 0;">mode_edit</i>
            Editar
          <% end %>
          <%= link_to replacement_request, method: :delete, data: { confirm: '¿Está seguro?' }, class:"text-danger btn btn-outline-danger btn-sm" do %>
            <i class="material-icons mr-1" style="top: 0;">remove_circle_outline</i>
            Eliminar
          <% end %>
        <% end %>
        <% if current_user.has_role?(:customer) && can?(:read, ReplacementProposal) && replacement_request.replacement_proposals.size > 0 %>
          <%= link_to replacement_proposals_path(replacement_request_id: replacement_request), data: { turbolinks: false }, class:"text-warning btn btn-outline-warning btn-sm" do %>
            <i class="material-icons mr-1" style="top: 0;">mark_email_read</i>
            Propuestas
          <% end %>
        <% end %>
        <% if can? :create, ReplacementProposal %>
          <%= link_to new_replacement_proposal_path(replacement_request_id: replacement_request), data: { turbolinks: false }, class:"text-warning btn btn-outline-warning btn-sm" do %>
            <i class="material-icons mr-1" style="top: 0;">mark_email_read</i>
            Agregar propueta
          <% end %>
        <% end %>
        <% if current_user.has_role?(:shop) && replacement_request.replacement_proposals.where(user_id: current_user.id).size == 0 %>
          <%= link_to ignore_replacement_request_path(replacement_request), data: { confirm: '¿Está seguro?' }, class:"text-danger btn btn-outline-danger btn-sm" do %>
            <i class="material-icons mr-1" style="top: 0;">close</i>
            Ignorar
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/replacement_requests/closed.html.erb
<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <div class="row">
      <div class="col-md-auto">
        <h1>
          <%= link_to dashboard_path, class:"btn btn-outline-dark btn-lg back-dashboard-button" do %>
            <i class="material-icons text-dark" style="top: 0;">arrow_back_ios_new</i>
          <% end %>
          Mis solicitudes cerradas
        </h1>
      </div>
      <div class="col">
        <%= search_form_for @rr_query, class: "form-inline ml-auto justify-content-end" do |f| %>
          <div class="form-group">
            <%= f.search_field :short_name_or_description_or_part_number_or_vehicle_brand_or_vehicle_model_cont, class: "form-control text-dark", placeholder: "Buscar" %>
          </div>
          <% if params[:q].present? %>
            <%= link_to replacement_requests_path, data: { turbolinks: false }, class: "btn btn-white btn-raised btn-fab btn-fab-mini btn-round" do %>
              <i class="material-icons">close</i>
            <% end %>
          <% else %>
            <button type="submit" class="btn btn-white btn-raised btn-fab btn-fab-mini btn-round">
              <i class="material-icons">search</i>
            </button>
          <% end %>
        <% end %>
      </div>
    </div>

    <% @replacement_requests.each_with_index do |replacement_request, index| %>
      <div class="card">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">email</i>
          </div>
          <div class="row">
            <div class="col-md-4 col-sm-6">
              <p class="card-category text-dark"><%= replacement_request.updated_at.strftime('%d/%m/%Y %H:%M') %> </p>
            </div>
            <div class="col-md-8 col-sm-6">
              <p class="card-category text-dark"><%= replacement_request.vehicle.brand %> <%= replacement_request.vehicle.model %> <%= replacement_request.vehicle.year %> </p>
            </div>
          </div>
          <h3 class="card-title"><%= replacement_request.short_name %></h3>
        </div>
        <div class="card-body">
          <% if replacement_request.part_number.present? %>
            <h4>P/N: <%= replacement_request.part_number %></h4>
          <% end %>
          <%= replacement_request.description.html_safe %>
        </div>
        <div class="card-footer">
          <div class="stats align-items-center">
            <% if can?(:manage, replacement_request) && replacement_request.state != 'closed' %>
              <%= link_to edit_replacement_request_path(replacement_request), data: { turbolinks: false }, class:"text-info btn btn-outline-info btn-sm" do %>
                <i class="material-icons text-dark mr-2" style="top: 0;">mode_edit</i>
                Editar
              <% end %>
              <%= link_to replacement_request, method: :delete, data: { confirm: '¿Está seguro?' }, class:"text-danger btn btn-outline-danger btn-sm" do %>
                <i class="material-icons mr-1" style="top: 0;">remove_circle_outline</i>
                Eliminar
              <% end %>
            <% end %>
            <% if can?(:read, ReplacementProposal) && replacement_request.replacement_proposals.size > 0 %>
              <%= link_to replacement_proposals_path(replacement_request_id: replacement_request), data: { turbolinks: false }, class:"text-warning btn btn-outline-warning btn-sm" do %>
                <i class="material-icons mr-1" style="top: 0;">mark_email_read</i>
                Propuestas
              <% end %>
            <% end %>
            <% if can? :create, ReplacementProposal %>
              <%= link_to new_replacement_proposal_path(replacement_request_id: replacement_request), data: { turbolinks: false }, class:"text-warning btn btn-outline-warning btn-sm" do %>
                <i class="material-icons mr-1" style="top: 0;">mark_email_read</i>
                Agregar propueta
              <% end %>
            <% end %>
            <% if current_user.has_role?(:shop) && replacement_request.replacement_proposals.size == 0 %>
              <%= link_to ignore_replacement_request_path(replacement_request), data: { confirm: '¿Está seguro?' }, class:"text-danger btn btn-outline-danger btn-sm" do %>
                <i class="material-icons mr-1" style="top: 0;">close</i>
                Ignorar
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <% if (index+1)%2 == 0 %>
        <p class="text-dark">
          <%= render 'home/ad_example' %>
        </p>
      <% end %>
    <% end %>

    <br>

  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

<% if current_user.has_role? :customer %>
  <div class="row justify-content-center">
    <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= link_to new_replacement_request_path, data: { turbolinks: false }, class:"btn btn-outline-primary btn-lg btn-block" do %>
        <i class="material-icons text-dark mr-3" style="top: 0;">flare</i>
        Solicitar repuesto
      <% end %>
    </div>
    <div class="col-md-1 col-sm-1"></div>
  </div>
  <br>
<% end %>

<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= render 'home/ad_example' %>
    </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

app/views/replacement_requests/index.html.erb
<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <div class="row">
      <div class="col-sm-12 col-lg-9">
        <h1 class="view-title">
          <%= link_to dashboard_path, class:"btn btn-outline-dark btn-lg back-dashboard-button" do %>
            <i class="material-icons text-dark" style="top: 0;">arrow_back_ios_new</i>
          <% end %>
          <% if current_user.has_role? :customer %>
            Mis solicitudes
          <% else %>
            Solicitudes
          <% end %>
        </h1>
      </div>
      <div class="col-sm-12 col-lg-3">
        <%= search_form_for @rr_query, class: "justify-content-sm-center justify-content-lg-end" do |f| %>
          <div class="form-group">
            <%= f.search_field :short_name_or_description_or_part_number_or_vehicle_brand_or_vehicle_model_cont, class: "form-control text-dark", placeholder: "Buscar" %>
          </div>
          <% if params[:q].present? %>
            <%= link_to replacement_requests_path, data: { turbolinks: false }, class: "btn btn-white btn-raised btn-fab btn-fab-mini btn-round" do %>
              <i class="material-icons">close</i>
            <% end %>
          <% else %>
            <button type="submit" class="btn btn-white btn-raised btn-fab btn-fab-mini btn-round d-none">
              <i class="material-icons">search</i>
            </button>
          <% end %>
        <% end %>
      </div>
    </div>

    <% if current_user.has_role? :shop %>
      <div id="accordion request-filters">
        <div class="card">
          <div class="card-header p-0" id="headingTwo">
            <h5 class="mb-0">
              <button class="btn btn-link px-2 py-1 btn-block d-flex justify-content-between collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Filtros
                <span class="material-icons m-0"> control_point </span>
              </button>
            </h5>
          </div>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body p-1 p-lg-3">
              <form action="<%= replacement_requests_path %>" metho="get">
                <div class="row p-0">
                  <div class="d-flex align-items-center col-lg-1 px-lg-0 py-lg-1 col-3">Marcas</div>
                  <div class="col-lg-11 px-lg-0 py-lg-1 col-9 ">
                    <div class="btn-group-toggle" data-toggle="buttons">
                      <% @all_brands.each_with_index do |brand, index| %>
                        <% is_active_brand = params[:filters].present? && params[:filters][:brands].present? && params[:filters][:brands].include?(brand) %>
                        <label class="btn btn-outline-info px-2 py-1 <%= is_active_brand ? 'active' : '' %>">
                          <input type="checkbox" autocomplete="off" <%= is_active_brand ? 'checked' : '' %> value="<%= brand %>" name="filters[brands][]" id="filters_brands"> <%= brand.upcase %>
                        </label>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="d-flex align-items-center col-lg-1 px-lg-0 py-lg-1 col-3">Años</div>
                  <div class="col-lg-11 px-lg-0 py-lg-1 col-9 ">
                    <div class="btn-group-toggle" data-toggle="buttons">
                      <% @all_years.each_with_index do |year, index| %>
                        <% is_active_year = params[:filters].present? && params[:filters][:years].present? && params[:filters][:years].include?(year.to_s) %>
                        <label class="btn btn-outline-info px-2 py-1 <%= is_active_year ? 'active' : '' %>">
                          <input type="checkbox" autocomplete="off" <%= is_active_year ? 'checked' : '' %> value="<%= year %>" name="filters[years][]" id="filters_years"> <%= year %>
                        </label>
                      <% end %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col p-1 p-lg-3">
                    <button type="submit" class="btn btn-block btn-info">
                      Continuar
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row">
      <% @replacement_requests.each_with_index do |replacement_request, index| %>
        <%= render 'request_item', replacement_request: replacement_request %>
        <% if (index+1)%3 == 0 %>
          <p class="text-dark col-sm-12">
            <%= render 'home/ad_example' %>
          </p>
        <% end %>
      <% end %>
    </div>

    <br>

  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

<% if current_user.has_role? :customer %>
  <div class="row justify-content-center">
    <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= link_to new_replacement_request_path, data: { turbolinks: false }, class:"btn btn-outline-primary btn-lg btn-block" do %>
        <i class="material-icons text-dark mr-3" style="top: 0;">flare</i>
        Solicitar repuesto
      <% end %>
    </div>
    <div class="col-md-1 col-sm-1"></div>
  </div>
  <br>
<% end %>

<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= render 'home/ad_example' %>
    </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

app/views/replacement_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @replacement_request.user_id %>
</p>

<p>
  <strong>Car:</strong>
  <%= @replacement_request.vehicle_id %>
</p>

<p>
  <strong>Part number:</strong>
  <%= @replacement_request.part_number %>
</p>

<p>
  <strong>Short name:</strong>
  <%= @replacement_request.short_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @replacement_request.description %>
</p>

<%= link_to 'Edit', edit_replacement_request_path(@replacement_request) %> |
<%= link_to 'Back', replacement_requests_path, data: { turbolinks: false } %>