config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  get 'home/index'
  get 'contact-us', to: 'home#contact_us'
  post 'contact-us', to: 'home#contact_us'
  get 'create', to: 'home#create'
  get 'privacy-policy', to: 'home#privacy_policy'
  get 'empresas', to: 'home#business'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard_shop', to: 'dashboard#shop'
  put 'users_add_onesignal_id', to: 'users#add_onesignal_id', defaults: { format: 'json' }
  get 'my_account', to: 'users#my_account'
  put 'update_account', to: 'users#update_account'
  get 'states_provinces/:country', to: 'application#states_provinces'
  get 'cities/:country/:state_province', to: 'application#cities'

  # devise_for :users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :replacement_requests do
    collection do
      get :closed
    end
    member do
      get :ignore
    end
  end
  resources :vehicles
  resources :shops
  resources :replacement_proposals do
    member do
      get :ignore
      get :accept
    end
  end
  defaults format: :json do
    get :search, to: 'replacement_proposals#search', as: 'replacement_proposal_search'
  end

  namespace :dario do
    resources :res_name
  end
end

app/models/replacement_proposal.rb
# frozen_string_literal: true

class ReplacementProposal < ApplicationRecord
  resourcify

  belongs_to :user
  belongs_to :shop
  belongs_to :replacement_request

  has_many_attached :photos

  validates :name, :price, :brand, :origin, :delivery_time, :conditions, presence: true

  scope :accepted, -> { where(state: 'accepted') }
  scope :recent, ->(number) { order(id: :desc).limit(number) }
end

app/controllers/replacement_proposals_controller.rb
# frozen_string_literal: true

class ReplacementProposalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_replacement_request, only: %i[show edit update new create]
  before_action :set_searchable_resource, only: %i[search new]
  load_and_authorize_resource

  # GET /replacement_proposals or /replacement_proposals.json
  def index
    if params[:replacement_request_id].present?
      @replacement_proposals = @replacement_proposals.where(replacement_request_id: params[:replacement_request_id].to_i)
    end
    if current_user.has_role? :customer
      @replacement_proposals = @replacement_proposals.where.not(id: IgnoredProposal.mine(current_user).map do |ir|
                                                                      ir.replacement_proposal_id
                                                                    end)
    end
    @replacement_proposals = @replacement_proposals.order(id: :desc)
  end

  # GET /replacement_proposals or /replacement_proposals.json
  def search
    @replacement_proposals = @replacement_proposals.order(id: :desc)

    respond_to do |format|
      format.html
      format.json do
        render 'replacement_proposals/search_results', location: @replacement_proposals.to_json, status: :ok
      end
    end
  end

  # GET /replacement_proposals/1 or /replacement_proposals/1.json
  def show
    redirect_to replacement_proposals_path(replacement_request_id: @replacement_proposal.replacement_request.id)
  end

  # GET /replacement_proposals/new
  def new
    @replacement_proposal = ReplacementProposal.new
    if params[:replacement_proposal_id].present?
      @replacement_proposal = ReplacementProposal.find params[:replacement_proposal_id]
    end
    @title = "Agregar una propuesta de repuesto para #{@replacement_request.short_name} del vehículo #{@replacement_request.vehicle.brand} #{@replacement_request.vehicle.model} #{@replacement_request.vehicle.year}"
  end

  # GET /replacement_proposals/1/edit
  def edit
    @title = "Editar la propuesta de repuesto para #{@replacement_request.short_name} del vehículo #{@replacement_request.vehicle.brand} #{@replacement_request.vehicle.model} #{@replacement_request.vehicle.year}"
  end

  # POST /replacement_proposals or /replacement_proposals.json
  def create
    @replacement_proposal = ReplacementProposal.new(replacement_proposal_params)
    @replacement_proposal.user = current_user

    respond_to do |format|
      if @replacement_proposal.save

        current_user.add_role :shop, @replacement_proposal
        @replacement_proposal.replacement_request.update(state: 'answered')

        if @replacement_proposal.replacement_request.user.onesignal_id.present?
          PushNotificationsHelper.new_proposal_created(@replacement_proposal,
                                                       replacement_proposals_path(replacement_request_id: @replacement_proposal.replacement_request_id))
        else
          ReplacementMailer.new_proposal(@replacement_proposal.replacement_request.user,
                                         @replacement_proposal).deliver_later
        end

        format.html do
          redirect_to replacement_proposals_path(replacement_request_id: @replacement_proposal.replacement_request.id),
                      notice: 'Propuesta creada correctamente.'
        end
        format.json { render :show, status: :created, location: @replacement_proposal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @replacement_proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replacement_proposals/1 or /replacement_proposals/1.json
  def update
    respond_to do |format|
      if @replacement_proposal.update(replacement_proposal_params)
        format.html do
          redirect_to replacement_proposals_path(replacement_request_id: @replacement_proposal.replacement_request.id),
                      notice: 'Propuesta actualizada correctamente.'
        end
        format.json { render :show, status: :ok, location: @replacement_proposal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @replacement_proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replacement_proposals/1 or /replacement_proposals/1.json
  def destroy
    @replacement_proposal.destroy
    respond_to do |format|
      format.html { redirect_to replacement_proposals_url, notice: 'Propuesta eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  # GET /replacement_proposals/1/ignore or /replacement_proposals/1/ignore.json
  def ignore
    IgnoredProposal.create(user: current_user, replacement_proposal: @replacement_proposal)
    redirect_to replacement_proposals_url(replacement_request_id: params[:replacement_request_id]),
                warning: 'Propuesta ignorada correctamente.'
  end

  # GET /replacement_proposals/1/accept or /replacement_proposals/1/accept.json
  def accept
    @replacement_proposal.update(state: 'accepted')
    @replacement_proposal.replacement_request.update(state: 'closed')
    if @replacement_proposal.shop.user.onesignal_id.present?
      PushNotificationsHelper.proposal_accepted(@replacement_proposal,
                                                replacement_proposals_path(replacement_request_id: @replacement_proposal.replacement_request_id))
    else
      ReplacementMailer.proposal_accepted(@replacement_proposal.shop.user, @replacement_proposal).deliver_later
    end
    redirect_to closed_replacement_requests_path, warning: 'Propuesta aceptada correctamente.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_replacement_proposal
    # @replacement_proposal = ReplacementProposal.find(params[:id])
  end

  def set_replacement_request
    request_id = if params[:replacement_proposal].present?
                   params[:replacement_proposal][:replacement_request_id]
                 else
                   params[:replacement_request_id]
                 end
    @replacement_request = ReplacementRequest.find(request_id)
  end

  # Only allow a list of trusted parameters through.
  def replacement_proposal_params
    params.require(:replacement_proposal).permit(:user_id, :shop_id, :replacement_request_id, :name, :price,
                                                 :original, :brand, :origin, :life_time, :target, :delivery_time, :conditions, photos: [])
  end

  def set_searchable_resource
    @rp_query = ReplacementProposal.accessible_by(current_ability).order(id: :desc).ransack(params[:q])
    @replacement_proposals = @rp_query.result(distinct: true).includes(:replacement_request)
  end
end

app/views/replacement_proposals/_form.html.erb
<%= form_with(model: replacement_proposal) do |form| %>
  <%= form.hidden_field :replacement_request_id, value: @replacement_request.id %>
  <% if replacement_proposal.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2>
        <%= I18n.t("errors.messages.not_saved", count: replacement_proposal.errors.count, resource: replacement_proposal.class.model_name.human.downcase) %>
      </h2>

      <ul>
        <% replacement_proposal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-header card-header-primary">
      <p class="card-category">Describa el repuesto que requiere lo mejor posible</p>
    </div>
    <div class="card-body">
      <div class="form-group">
        <%= form.label :shop_id, class:"bmd-label-floating" %>
        <select class="form-control" name="replacement_proposal[shop_id]" id="replacement_proposal_shop_id">
          <%= options_for_select(current_user.shops.collect{ |t| [ "#{t.ruc} - #{t.name}", t.id ] }) %>
        </select>
      </div>

      <div class="form-group">
        <%= form.label :name, class:"bmd-label-floating" %>
        <%= form.text_field :name, class:"form-control", required: true %>
      </div>

      <div class="row">
        <div class="col-sm-12 col-md-6">
          <div class="input-group">
            <%= form.label :price %>
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="material-icons">attach_money</i>
              </span>
            </div>
            <%= form.text_field :price, class:"form-control", required: true %>
          </div>
        </div>
        <div class="col-sm-12 col-md-6">
          <div class="form-check">
            <label class="form-check-label">
              <%= form.check_box :original, class:"form-check-input" %>
              Repuesto original
              <span class="form-check-sign">
                <span class="check"></span>
              </span>
            </label>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= form.label :brand, class:"bmd-label-floating" %>
        <%= form.text_field :brand, class:"form-control", required: true %>
      </div>

      <div class="form-group">
        <%= form.label :origin, class:"bmd-label-floating" %>
        <%= form.text_field :origin, class:"form-control", required: true %>
      </div>

      <div class="form-group">
        <%= form.label :life_time, class:"bmd-label-floating" %>
        <%= form.text_field :life_time, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :target, class:"bmd-label-floating" %>
        <%= form.text_field :target, class:"form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :delivery_time, class:"bmd-label-floating" %>
        <%= form.text_field :delivery_time, class:"form-control", required: true %>
      </div>

      <div class="form-group">
        <%= form.label :conditions, class:"bmd-label-floating" %>
        <%= form.text_field :conditions, class:"form-control", required: true %>
      </div>

      <div class="form-group">
        <%= form.label :photos, "Agregar Fotos", class:"text-primary btn btn-outline-primary btn-sm" %>
        <%= form.file_field :photos, class:"form-control-file", multiple: true %>
        <div class="add_photo row"></div>
      </div>
    </div>
    
    <div class="card-footer">
      <div class="stats align-items-center">
        <%= form.submit 'Guardar', class:"text-info btn btn-outline-info btn-sm" %>
        &nbsp;&nbsp;
        <%= link_to 'Cancelar', replacement_proposals_path, data: { turbolinks: false }, class:"text-danger btn btn-outline-danger btn-sm" %>
      </div>
    </div>
  </div>

<% end %>

<script type="text/javascript">
  replacement_proposal_photos.onchange = evt => {
    const v_files = Array.from(replacement_proposal_photos.files);
    console.log(v_files);
    v_files.forEach(item => {
      console.log(item);
      if (item) {
        prev_photo = $('<div class="col-sm-12 col-md-4"><img src="'+URL.createObjectURL(item)+'" alt="your image" style="width: 100%; display: block;" /></div>');
        $('.add_photo').append(prev_photo);
      }
    });
  }
</script>

app/views/replacement_proposals/_proposal_item.erb
<div class="col-md-6 col-sm-12">
  <div class="card">
    <div class="card-header card-header-warning">
      <h4 class="card-title"><%= replacement_proposal.replacement_request.vehicle.brand %> <%= replacement_proposal.replacement_request.vehicle.model %> <%= replacement_proposal.replacement_request.vehicle.year %></h4>
    </div>
    <div class="card-body">
      <h3 class="card-title">
        <%= replacement_proposal.name %> | <%= replacement_proposal.brand %>
      </h3>
      <h4 class="text-dark alert-link">Detalles</h4>
      <ul>
        <li class="text-dark"><strong>Pais de origen:</strong> <%= replacement_proposal.origin %></li>
        <li class="text-dark"><strong>Vida útil:</strong> <%= replacement_proposal.life_time %></li>
        <% if replacement_proposal.target.present? %>
          <li class="text-dark"><strong>Aplica para:</strong> <%= replacement_proposal.target %></li>
        <% end %>
        <li class="text-dark"><strong>Tiempo de entrega:</strong> <%= replacement_proposal.delivery_time %></li>
      </ul>
      <h4 class="text-dark alert-link">Condiciones de entrega</h4>
      <p class="text-dark"><%= replacement_proposal.conditions.html_safe %></p>
      <% if replacement_proposal.photos.any? %>
        <h4 class="text-dark alert-link">Fotos del repuesto</h4>
        <div class="image-gallery">
          <% replacement_proposal.photos.each_with_index do |photo, index| %>
            <div class="image-element">
              <% if photo.representable? && (["image/png", "image/jpeg", "image/png", "image/gif"].include?(photo.content_type)) %>
                <%= image_tag photo.variant(resize_to_limit: [350, 350]), class: "img-fluid rounded mx-auto d-block" %>
              <% else %>
                <%= link_to rails_blob_path(photo, disposition: "attachment") do %>
                  <div class="download-icon">
                    <span class="material-icons"> cloud_download </span>
                  </div>
                  <%= image_tag "quien_tiene_logo_n.png", alt: "Descargue el archivo", width: 350 %>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
      <p class="text-dark">
        <i class="material-icons text-warning" style="top: 5px; position: relative;">store</i> <%= replacement_proposal.shop.name.upcase %> <small><%= replacement_proposal.shop.ruc %></small><br>
        <i class="material-icons text-warning" style="top: 5px; position: relative;">explore</i> <%= replacement_proposal.shop.address %> - <%= replacement_proposal.shop.sector %><br>
        <% if replacement_proposal.shop.phone2.present? %>
          <i class="material-icons text-warning" style="top: 5px; position: relative;">phone</i> <%= replacement_proposal.shop.phone2 %><br>
        <% end %>
        <% if replacement_proposal.shop.city.present? %>
          <span class="material-icons text-warning" style="position: relative; top: 5px;">location_city</span> <%= replacement_proposal.shop.city %><br>
        <% end %>
      </p>
      <% if current_user.has_role?(:customer) %>
        <a href="https://api.whatsapp.com/send?<%= URI.encode_www_form(phone: "+593#{replacement_proposal.shop.phone1[1..-1]}", text: "Quisiera comprar el repuesto de su propuesta en https://quientiene.com#{replacement_proposals_path(replacement_request_id: replacement_proposal.replacement_request_id)}") %>" class="text-info btn btn-outline-info btn-sm" target="_blank">
          <i class="material-icons text-info mr-2" style="top: 0;">textsms</i> Contactar con la empresa
        </a>
      <% end %>
      <a class="btn btn-outline-warning btn-block disabled text-warning btn-lg" role="button" aria-disabled="true">
        <strong>$<%= replacement_proposal.price %></strong>
      </a>
    </div>
    <div class="card-footer">
      <div class="stats align-items-center">
        <% if can?(:manage, replacement_proposal) && params[:q].nil? %>
          <%= link_to edit_replacement_proposal_path(replacement_proposal, replacement_request_id: replacement_proposal.replacement_request.id), class:"text-info btn btn-outline-info btn-sm" do %>
            <i class="material-icons text-dark mr-2" style="top: 0;">mode_edit</i>
            Editar
          <% end %>
          <%= link_to replacement_proposal, method: :delete, data: { confirm: '¿Está seguro?' }, class:"text-danger btn btn-outline-danger btn-sm" do %>
            <i class="material-icons mr-1" style="top: 0;">remove_circle_outline</i>
            Eliminar
          <% end %>
        <% end %>

        <% if current_user.has_role?(:customer) %>
          <% if replacement_proposal.state == 'accepted' %>
            <%= link_to "javascript: void(0);", class:"text-success btn btn-outline-success btn-sm", disabled: true do %>
              <i class="material-icons mr-1" style="top: 0;">done</i>
              Propuesta aceptada
            <% end %>
          <% else %>
            <%= link_to accept_replacement_proposal_path(replacement_proposal, replacement_request_id: replacement_proposal.replacement_request_id), data: { confirm: '¿Está seguro?' }, class:"text-success btn btn-outline-success btn-sm" do %>
              <i class="material-icons mr-1" style="top: 0;">done</i>
              Aceptar
            <% end %>
          <% end %>
        <% end %>
        <% if current_user.has_role?(:shop) && (params[:q].present? || params[:action] == 'new') %>
          <%= link_to new_replacement_proposal_path(replacement_request_id: params[:replacement_request_id], replacement_proposal_id: replacement_proposal.id), class: "btn btn-outline-warning btn-block text-warning content-copy" do %>
            <i class="material-icons mr-1" style="top: 0;">content_copy</i>
            Usar esta propuesta
          <% end %>
        <% end %>
        <% if current_user.has_role?(:customer) && replacement_proposal.state != 'accepted' %>
          <%= link_to ignore_replacement_proposal_path(replacement_proposal, replacement_request_id: replacement_proposal.replacement_request_id), data: { confirm: '¿Está seguro?' }, class:"text-danger btn btn-outline-danger btn-sm" do %>
            <i class="material-icons mr-1" style="top: 0;">close</i>
            Ignorar
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/replacement_proposals/_request.erb
<div class="card">
  <div class="card-header card-header-success card-header-icon">
    <div class="card-icon">
      <i class="material-icons">email</i>
    </div>
    <div class="row">
      <div class="col-md-4 col-sm-6">
        <p class="card-category text-dark"><%= replacement_request.updated_at.strftime('%d/%m/%Y %H:%M') %> </p>
      </div>
      <div class="col-md-8 col-sm-6">
        <p class="card-category text-dark"><%= replacement_request.vehicle.brand %> <%= replacement_request.vehicle.model %> <%= replacement_request.vehicle.year %> </p>
      </div>
    </div>
    <h3 class="card-title"><%= replacement_request.short_name %></h3>
  </div>
  <div class="card-body">
    <% if replacement_request.part_number.present? %>
      <h4>P/N: <%= replacement_request.part_number %></h4>
    <% end %>
    <%= replacement_request.description.html_safe %>
  </div>
</div>

app/views/replacement_proposals/edit.html.erb
<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <h1>
      <%= link_to dashboard_path, class:"btn btn-outline-dark btn-lg back-dashboard-button" do %>
        <i class="material-icons text-dark" style="top: 0;">arrow_back_ios_new</i>
      <% end %>
      Editar Propuesta
    </h1>
    <%= render 'replacement_requests/request_item', replacement_request: @replacement_request %>
    <%= render 'form', replacement_proposal: @replacement_proposal %>
  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

<br>

<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= render 'home/ad_example' %>
    </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

app/views/replacement_proposals/index.html.erb
<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <h1>
      <%= link_to dashboard_path, class:"btn btn-outline-dark btn-lg back-dashboard-button" do %>
        <i class="material-icons text-dark" style="top: 0;">arrow_back_ios_new</i>
      <% end %>
      Propuestas de repuestos
    </h1>
    <div class="row">
      <% @replacement_proposals.each do |replacement_proposal| %>
        <%= render 'proposal_item', replacement_proposal: replacement_proposal %>
      <% end %>
    </div>

    <br>

  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= render 'home/ad_example' %>
    </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

<% if false %>
  <% @replacement_proposals.each do |replacement_proposal| %>
    <tr>
      <td><%= replacement_proposal.price %></td>
      <td><%= replacement_proposal.original %></td>
      <td></td>
      
      <td><%= link_to 'Show', replacement_proposal %></td>
    </tr>
  <% end %>
<% end %>

app/views/replacement_proposals/new.html.erb
<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <h1>
      <%= link_to dashboard_shop_path, class:"btn btn-outline-dark btn-lg back-dashboard-button" do %>
        <i class="material-icons text-dark" style="top: 0;">arrow_back_ios_new</i>
      <% end %>
      Agregar propuesta
    </h1>

    <%= render 'replacement_requests/request_item', replacement_request: @replacement_request %>
    <%= render 'form', replacement_proposal: @replacement_proposal %>
  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

<br>

<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
    <div class="col">
      <%= render 'home/ad_example' %>
    </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

<br>

<div class="row justify-content-center">
  <div class="col-md-1 col-sm-1"></div>
  <div class="col">
    <% if @rp_query.present? %>
      <h2>
        Propuestas similares
      </h2>
      <%= search_form_for @rp_query, url: replacement_proposal_search_path(replacement_request_id: params[:replacement_request_id]), remote: true, :html => {:'data-type' => 'json'}, class: "justify-content-sm-center justify-content-lg-end" do |f| %>
        <%= hidden_field_tag :replacement_request_id, params[:replacement_request_id].to_s %>
        <div class="form-group">
          <%= f.search_field :name_or_brand_or_target_or_origin_cont, class: "form-control text-dark", placeholder: "Buscar" %>
        </div>
        <% if params[:q].present? %>
          <%= link_to replacement_requests_path, data: { turbolinks: false }, class: "btn btn-white btn-raised btn-fab btn-fab-mini btn-round" do %>
            <i class="material-icons">close</i>
          <% end %>
        <% else %>
          <button type="submit" class="btn btn-white btn-raised btn-fab btn-fab-mini btn-round d-none">
            <i class="material-icons">search</i>
          </button>
        <% end %>
      <% end %>
      
      <div class="row" id="previous-proposals">
        <% @replacement_proposals.each do |replacement_proposal| %>
          <%= render 'proposal_item', replacement_proposal: replacement_proposal %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="col-md-1 col-sm-1"></div>
</div>

app/views/replacement_proposals/search_results.json.erb
<% @replacement_proposals.each do |replacement_proposal| %>
  <%= render 'proposal_item', replacement_proposal: replacement_proposal %>
<% end %>

app/views/replacement_proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @replacement_proposal.user_id %>
</p>

<p>
  <strong>Shop:</strong>
  <%= @replacement_proposal.shop_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @replacement_proposal.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @replacement_proposal.price %>
</p>

<p>
  <strong>Original:</strong>
  <%= @replacement_proposal.original %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @replacement_proposal.brand %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @replacement_proposal.origin %>
</p>

<p>
  <strong>Life time:</strong>
  <%= @replacement_proposal.life_time %>
</p>

<p>
  <strong>Target:</strong>
  <%= @replacement_proposal.target %>
</p>

<p>
  <strong>Delivery time:</strong>
  <%= @replacement_proposal.delivery_time %>
</p>

<p>
  <strong>Conditions:</strong>
  <%= @replacement_proposal.conditions %>
</p>

<%= link_to 'Edit', edit_replacement_proposal_path(@replacement_proposal) %> |
<%= link_to 'Back', replacement_proposals_path, data: { turbolinks: false } %>