config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: 'home#index'

  get 'home/index'
  get 'contact-us', to: 'home#contact_us'
  post 'contact-us', to: 'home#contact_us'
  get 'create', to: 'home#create'
  get 'privacy-policy', to: 'home#privacy_policy'
  get 'empresas', to: 'home#business'
  get 'dashboard', to: 'dashboard#index'
  get 'dashboard_shop', to: 'dashboard#shop'
  put 'users_add_onesignal_id', to: 'users#add_onesignal_id', defaults: { format: 'json' }
  get 'my_account', to: 'users#my_account'
  put 'update_account', to: 'users#update_account'
  get 'states_provinces/:country', to: 'application#states_provinces'
  get 'cities/:country/:state_province', to: 'application#cities'

  # devise_for :users
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :replacement_requests do
    collection do
      get :closed
    end
    member do
      get :ignore
    end
  end
  resources :vehicles
  resources :shops
  resources :replacement_proposals do
    member do
      get :ignore
      get :accept
    end
  end
  defaults format: :json do
    get :search, to: 'replacement_proposals#search', as: 'replacement_proposal_search'
  end

  namespace :dario do
    resources :res_name
  end
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

  <link rel="profile" href="https://gmpg.org/xfn/11" />
  <link rel="apple-touch-icon" sizes="180x180" href="https://quientiene.com/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="https://quientiene.com/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="https://quientiene.com/favicon/favicon-16x16.png">
  <link rel="mask-icon" href="https://quientiene.com/favicon/safari-pinned-tab.svg" color="#343434">
  <link rel="manifest" href="https://quientiene.com/favicon/site.webmanifest">
  <meta name="msapplication-TileColor" content="#343434">
  <meta name="theme-color" content="#343434">
  <meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />

  <title>
    <% if @title.blank? %>
      QuienTinene.com :: Encuentre el repuesto que está buscando
    <% else %>
      QuienTinene.com :: <%= @title %>
    <% end %>
  </title>
  <meta name="description" content="Todos los locales en un solo lugar, encuentre el repuesto que tanto busca." />
  <link rel="canonical" href="https://quientiene.com/" />
  <meta property="og:locale" content="es_MX" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="<%= @title %>" />
  <meta property="og:description" content="Todos los locales en un solo lugar, encuentre el repuesto que tanto busca." />
  <meta property="og:url" content="https://quientiene.com/" />
  <meta property="og:site_name" content="QuienTiene" />
  <meta property="article:modified_time" content="<%= DateTime.now.strftime("%Y-%m-%dT%H:%M:%S+00:00") %>" />
  <meta property="og:image" content="https://quientiene.com/assets/quien_tiene_logo_b-40f9d65242b0044e319e88a3dc3bd6ed44146b22ef46b469933ed4fe1a080020.png" />
  <meta property="og:image:width" content="900" />
  <meta property="og:image:height" content="479" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:image" content="https://quientiene.com/assets/quien_tiene_logo_b-40f9d65242b0044e319e88a3dc3bd6ed44146b22ef46b469933ed4fe1a080020.png" />
  <meta name="twitter:site" content="@dario_chuquilla" />
  <meta name="twitter:label1" content="Est. reading time" />
  <meta name="twitter:data1" content="1 minuto" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'false' %>
  <script src="/js_core/10jquery-3.3.1.min.js" data-turbolinks-track="false"></script>
  <script async src="/js_core/20popper.min.js" data-turbolinks-track="false"></script>
  <script async src="/js_core/35bootstrap-material-design.min.js" data-turbolinks-track="false"></script>
  <script async src="/js_core/40material-dashboard.js" data-turbolinks-track="false"></script>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'false', async: true %>

  <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-0HKQTSW8VY"" data-turbolinks-track="false"></script>
    <script type="text/javascript">
      (async function() {
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-0HKQTSW8VY');
      })();
    </script>
  <!-- END Global site tag (gtag.js) - Google Analytics -->

  <% if user_signed_in? %>
    <!-- OneSignal code -->
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    <script>
      window.OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
        OneSignal.init({
          appId: "19562cd9-e931-441f-b7ca-171be04a5224",
          autoRegister: false,
          allowLocalhostAsSecureOrigin: true,
          notifyButton: {
            enable: true
          },
          webhooks: {
            cors: true
          }
        });
        OneSignal.on('subscriptionChange', function (isSubscribed) {
          if (isSubscribed) {
            OneSignal.getUserId(function(userId) {
              var user_params = { onesignal_id: userId };
              $.ajax({
                url: '<%= users_add_onesignal_id_url %>.json',
                dataType: "json",
                type: "put",
                async: true,
                data: { onesignal_id: userId },
                success: function (data) {
                  var user = data;
                  OneSignal.push(["sendTag", "user_id", user.id]);
                  OneSignal.push(["sendTag", "user_name", user.name]);
                  OneSignal.push(["sendTag", "user_email", user.email]);
                  <% if current_user.has_role?(:shop) %>
                    OneSignal.push(["sendTag", "user_type", 'store']);
                  <% else %>
                    OneSignal.push(["sendTag", "user_type", 'client']);
                  <% end %>
                },
                error: function (xhr, exception) {
                  var msg = "";
                  if (xhr.status === 0) {
                    msg = "Not connect.\n Verify Network." + xhr.responseText;
                  } else if (xhr.status == 404) {
                    msg = "Requested page not found. [404]" + xhr.responseText;
                  } else if (xhr.status == 500) {
                    msg = "Internal Server Error [500]." +  xhr.responseText;
                  } else if (exception === "parsererror") {
                    msg = "Requested JSON parse failed.";
                  } else if (exception === "timeout") {
                    msg = "Time out error." + xhr.responseText;
                  } else if (exception === "abort") {
                    msg = "Ajax request aborted.";
                  } else {
                    msg = "Error:" + xhr.status + " " + xhr.responseText;
                  }
                  console.log(msg);
                }
              }); 
            });
          }
        });
      });
    </script>
    <!-- ENDOneSignal code -->
    <% if params[:controller] == 'Admin::DashboardController' %>
      <link rel="stylesheet" media="screen" href="/active_admin.css" />
    <% end %>
  <% end %>

  <!-- Facebook Pixel Code -->
    <script defer src="/js_core/62fb-pixel.js" data-turbolinks-track="false"></script>
    <noscript><img height="1" width="1" src="https://www.facebook.com/tr?id=4715094701868400&ev=PageView&noscript=1"/></noscript>
  <!-- End Facebook Pixel Code -->

</head>

<body class="<%= ['index', 'new'].include?(params[:action]) && ['users/sessions', 'users/registrations', 'devise/unlocks','home', 'devise/passwords'].include?(params[:controller]) ? 'is-boxed' : '' %>">
  <% if user_signed_in? %>
    <nav class="user-navigation navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to root_path, class:"navbar-brand btn btn-outline" do %>
          <%= image_tag "quien_tiene_logo_b.png", height: "50" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <% if current_user.has_role?(:customer) %>
              <li class="nav-item btn btn-outline">
                <%= link_to "Panel de control", dashboard_path, class:"nav-link text-white" %>
              </li>
              <li class="nav-item btn btn-outline">
                <%= link_to "Mis Solicitudes", replacement_requests_path, data: { turbolinks: false }, class: "nav-link text-white" %>
              </li>
              <li class="nav-item btn btn-outline">
                <%= link_to "Mis vehículos", vehicles_path, data: { turbolinks: false }, class: "nav-link text-white" %>
              </li>
            <% end %>
            <% if current_user.has_role?(:shop) %>
              <li class="nav-item btn btn-outline">
                <%= link_to "Panel de control", dashboard_shop_path, class:"nav-link text-white" %>
              </li>
              <li class="nav-item btn btn-outline">
                <%= link_to "Mils locales", shops_path, class:"nav-link text-white" %>
              </li>
            <% end %>
            <li class="nav-item btn btn-outline">
              <%= link_to "Mi cuenta", my_account_path, class: "nav-link text-white" %>
            </li>
            <li class="nav-item btn btn-outline">
              <%= link_to "Salir", destroy_user_session_path, method: :delete, class:"nav-link text-white" %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  <% end %>
  <% if notice %>
    <p class="alert fixed-position alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert fixed-position alert-danger"><%= alert %></p>
  <% end %>
  <% if warning %>
    <p class="alert fixed-position alert-warning"><%= warning %></p>
  <% end %>
  
  <%= yield %>
  
  <% if  params[:controller] == 'home' %>
    <%= render "home/shared/footer" %>
  <% else %>
    <%= render "home/shared/footer_users" %>
  <% end %>
</body>
</html>

app/views/layouts/landing.html.erb
<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

  <link rel="profile" href="https://gmpg.org/xfn/11" />
  <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
  <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#343434">
  <link rel="manifest" href="/favicon/site.webmanifest">
  <meta name="msapplication-TileColor" content="#343434">
  <meta name="theme-color" content="#343434">
  <meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />

  <title>
    <% if @title.blank? %>
      QuienTinene.com :: Encuentre el repuesto que está buscando
    <% else %>
      QuienTinene.com :: <%= @title %>
    <% end %>
  </title>
  <meta name="description" content="Todos los locales en un solo lugar, encuentre el repuesto que tanto busca." />
  <link rel="canonical" href="https://quientiene.com/" />
  <meta property="og:locale" content="es_MX" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="<%= @title %>" />
  <meta property="og:description" content="Todos los locales en un solo lugar, encuentre el repuesto que tanto busca." />
  <meta property="og:url" content="https://quientiene.com/" />
  <meta property="og:site_name" content="QuienTiene" />
  <meta property="article:modified_time" content="<%= DateTime.now.strftime("%Y-%m-%dT%H:%M:%S+00:00") %>" />
  <meta property="og:image" content="/assets/quien_tiene_logo_b-40f9d65242b0044e319e88a3dc3bd6ed44146b22ef46b469933ed4fe1a080020.png" />
  <meta property="og:image:width" content="900" />
  <meta property="og:image:height" content="479" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:image" content="/assets/quien_tiene_logo_b-40f9d65242b0044e319e88a3dc3bd6ed44146b22ef46b469933ed4fe1a080020.png" />
  <meta name="twitter:site" content="@dario_chuquilla" />
  <meta name="twitter:label1" content="Est. reading time" />
  <meta name="twitter:data1" content="1 minuto" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'false' %>
  <link rel="stylesheet" data-turbolinks-track="false" href="/landing-assets/css/bootstrap.min.css">
	<link rel="stylesheet" data-turbolinks-track="false" href="/landing-assets/css/ionicons.min.css">
	<link rel="stylesheet" data-turbolinks-track="false" href="/landing-assets/css/owl.carousel.css">
	<link rel="stylesheet" data-turbolinks-track="false" href="/landing-assets/css/owl.theme.css">
	<link rel="stylesheet" data-turbolinks-track="false" href="/landing-assets/css/animate.css">
	<link rel="stylesheet" data-turbolinks-track="false" href="/landing-assets/css/style.css">

  <!-- fonts -->
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic|Roboto+Condensed:300italic,400italic,700italic,400,300,700|Oxygen:400,300,700' rel='stylesheet'>

	<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!--[if lt IE 9]>
        <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->

  <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-0HKQTSW8VY"" data-turbolinks-track="false"></script>
    <script type="text/javascript">
      (async function() {
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-0HKQTSW8VY');
      })();
    </script>
  <!-- END Global site tag (gtag.js) - Google Analytics -->

  <% if user_signed_in? %>
    <!-- OneSignal code -->
    <%= render 'shared/one_signal' %>
    <!-- ENDOneSignal code -->
    <% if params[:controller] == 'Admin::DashboardController' %>
      <link rel="stylesheet" media="screen" href="/active_admin.css" />
    <% end %>
  <% end %>

  <!-- Facebook Pixel Code -->
    <script defer src="/js_core/62fb-pixel.js" data-turbolinks-track="false"></script>
    <noscript><img height="1" width="1" src="https://www.facebook.com/tr?id=4715094701868400&ev=PageView&noscript=1"/></noscript>
  <!-- End Facebook Pixel Code -->

</head>

<body id="home">
  
  <%= yield %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'false', async: true %>
  	<!-- All the scripts -->

	<script src="/landing-assets/js/jquery-2.1.3.min.js"></script>
	<script src="/landing-assets/js/bootstrap.min.js"></script>
	<script src="/landing-assets/js/wow.min.js"></script>
	<script src="/landing-assets/js/owl.carousel.js"></script>
	<script src="/landing-assets/js/script.js"></script>
</body>
</html>